""""add_dhcp_pool_and_update_vmconfig"

Revision ID: 20f0a2dcaa88
Revises: 216b0c65ff2c
Create Date: 2025-06-14 15:54:40.696944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f0a2dcaa88'
down_revision: Union[str, None] = '216b0c65ff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhcp_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('range_start', sa.String(), nullable=False),
    sa.Column('range_stop', sa.String(), nullable=False),
    sa.Column('default_router', sa.String(), nullable=True),
    sa.Column('dns_servers', sa.String(), nullable=True),
    sa.Column('lease_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('vms_network_config', schema=None) as batch_op: # Corrected table name
        batch_op.add_column(sa.Column('hostname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dhcp_pool_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vm_network_configs_dhcp_pool_id', 'dhcp_pools', ['dhcp_pool_id'], ['id'])
        # If internal_ip can now be nullable if dhcp_pool_id is set
        batch_op.alter_column('internal_ip', existing_type=sa.VARCHAR(), nullable=True)


    # Rename ip_pools to simple_ip_range_pools
    op.rename_table('ip_pools', 'simple_ip_range_pools')
    # Rename port_pools to simple_port_range_pools
    op.rename_table('port_pools', 'simple_port_range_pools')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert rename simple_port_range_pools to port_pools
    op.rename_table('simple_port_range_pools', 'port_pools')
    # Revert rename simple_ip_range_pools to ip_pools
    op.rename_table('simple_ip_range_pools', 'ip_pools')

    with op.batch_alter_table('vms_network_config', schema=None) as batch_op: # Corrected table name
        batch_op.drop_constraint('fk_vm_network_configs_dhcp_pool_id', type_='foreignkey')
        batch_op.drop_column('dhcp_pool_id')
        batch_op.drop_column('hostname')
        # Revert internal_ip nullability, assuming it was not nullable before
        # This might need adjustment based on the original schema for internal_ip
        batch_op.alter_column('internal_ip', existing_type=sa.VARCHAR(), nullable=False)


    op.drop_table('dhcp_pools')
    # ### end Alembic commands ###
