"""Initial database schema

Revision ID: 216b0c65ff2c
Revises: 
Create Date: 2025-06-09 22:00:46.527483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216b0c65ff2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('ip_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_ip', sa.String(), nullable=False),
    sa.Column('start_octet', sa.Integer(), nullable=False),
    sa.Column('end_octet', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('port_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_port', sa.Integer(), nullable=False),
    sa.Column('end_port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # Create vms_network_config table first
    op.create_table('vms_network_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('internal_ip', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_ip'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('machine_id')
    )
    # Create vm_port_rules table next, as it has a FK to vms_network_config
    op.create_table('vm_port_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('port_type', sa.Enum('ssh', 'http', 'https', name='porttype'), nullable=True),
    sa.Column('external_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('enabled', 'disabled', 'not_active', name='portstatus'), nullable=True),
    sa.Column('nat_rule_number', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Enum('tcp', 'udp', 'tcp_udp', 'all', name='portprotocol'), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('custom_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms_network_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_port'),
    sa.UniqueConstraint('nat_rule_number')
    )
    # Now add columns to vm_port_rules if they were missed during initial table creation by autogenerate
    # However, these columns are already included in the create_table above, so these add_column calls might be redundant
    # or were intended for a scenario where the table was created with fewer columns initially.
    # For a clean initial schema, it's better to define all columns in create_table.
    # I will keep them commented out for now as they are defined in the create_table call.
    # op.add_column('vm_port_rules', sa.Column('protocol', sa.Enum('tcp', 'udp', 'tcp_udp', 'all', name='portprotocol'), nullable=True))
    # op.add_column('vm_port_rules', sa.Column('source_ip', sa.String(), nullable=True))
    # op.add_column('vm_port_rules', sa.Column('custom_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('vm_port_rules', 'custom_description') # Already handled by drop_table
    # op.drop_column('vm_port_rules', 'source_ip') # Already handled by drop_table
    # op.drop_column('vm_port_rules', 'protocol') # Already handled by drop_table
    op.drop_table('vm_port_rules')
    op.drop_table('vms_network_config')
    op.drop_table('users')
    op.drop_table('port_pools')
    op.drop_table('ip_pools')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
