""""update_dhcppool_and_vmnetworkconfig_models"

Revision ID: 483828424643
Revises: 31c950d95a37
Create Date: 2025-06-14 20:31:26.107981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483828424643'
down_revision: Union[str, None] = '31c950d95a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dhcp_pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subnet', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('ip_range_start', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('ip_range_end', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('gateway', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('domain_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('range_stop')
        batch_op.drop_column('default_router')
        batch_op.drop_column('network')
        batch_op.drop_column('range_start')

    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_firewall_rules_policy_id_rule_number'), type_='unique')
        batch_op.create_unique_constraint('_policy_rule_uc', ['policy_id', 'rule_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall_rules', schema=None) as batch_op:
        batch_op.drop_constraint('_policy_rule_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_firewall_rules_policy_id_rule_number'), ['policy_id', 'rule_number'])

    with op.batch_alter_table('dhcp_pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('range_start', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('network', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('default_router', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('range_stop', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('domain_name')
        batch_op.drop_column('gateway')
        batch_op.drop_column('ip_range_end')
        batch_op.drop_column('ip_range_start')
        batch_op.drop_column('subnet')

    # ### end Alembic commands ###
