""""add_static_route_table"

Revision ID: d1c8c35fd605
Revises: 483828424643
Create Date: 2025-06-14 21:15:32.806866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c8c35fd605'
down_revision: Union[str, None] = '483828424643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('next_hop', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination', 'next_hop', 'user_id', name='_destination_nexthop_user_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_routes')
    # ### end Alembic commands ###
